query Q($login: String!, $last: Int!, $before: String) {
  user(login: $login) {
    pullRequests(last: $last, before: $before) {
      pageInfo {
        startCursor
        endCursor
      }
      edges {
        node {
          title
          url
          repository {
            name
          }
          createdAt
          author {
            login
            url
          }
        }
      }
    }
  }
}
