// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var GithubApi = require("github-api");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");

function makePullRequest(title, head, $staropt$star, $staropt$star$1, maintainer_can_modify, repo) {
  var base = $staropt$star ? $staropt$star[0] : "master";
  var body = $staropt$star$1 ? $staropt$star$1[0] : "";
  return repo.createPullRequest({
              title: title,
              head: head,
              base: base,
              body: body,
              maintainer_can_modify: Js_undefined.fromOption(maintainer_can_modify)
            }, (function (prim) {
                console.log(prim);
                return /* () */0;
              }));
}

var Repository = /* module */[/* makePullRequest */makePullRequest];

var Issue = /* module */[];

function make(username, password, token, _) {
  var exit = 0;
  if (username || password || token) {
    exit = 1;
  } else {
    return new GithubApi(undefined);
  }
  if (exit === 1) {
    return new GithubApi({
                username: Js_undefined.fromOption(username),
                password: Js_undefined.fromOption(password),
                token: Js_undefined.fromOption(token)
              });
  }
  
}

exports.Repository = Repository;
exports.Issue = Issue;
exports.make = make;
/* github-api Not a pure module */
