// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var GitHub$GithubGeppou = require("./GitHub.bs.js");

var __x = GitHub$GithubGeppou.make(/* None */0, /* None */0, /* Some */[process.env.GITHUB_API_TOKEN], /* () */0).getIssues("kogai", "typed_i18n");

__x.listIssueEvents(10, (function (prim) {
          console.log(prim);
          return /* () */0;
        })).then((function (result) {
        console.log(result);
        return Promise.resolve(/* () */0);
      }));

/*  Not a pure module */
